In [3]:
import os
os.chdir("C:/Users/Sai/Desktop/Data Sets")

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing
dataset=pd.read_csv('turbine.csv')

In [5]:
dataset

,﻿Date/Time,LV ActivePower (kW),Wind Speed (m/s),Theoretical_Power_Curve (KWh),Wind Direction (°)
0,01 01 2018 00:00,380.047791,5.311336,416.328908,259.994904
1,01 01 2018 00:10,453.769196,5.672167,519.917511,268.641113
2,01 01 2018 00:20,306.376587,5.216037,390.900016,272.564789
3,01 01 2018 00:30,419.645905,5.659674,516.127569,271.258087
4,01 01 2018 00:40,380.650696,5.577941,491.702972,265.674286
5,01 01 2018 00:50,402.391998,5.604052,499.436385,264.578613
6,01 01 2018 01:00,447.605713,5.793008,557.372363,266.163605
7,01 01 2018 01:10,387.242188,5.306050,414.898179,257.949493
8,01 01 2018 01:20,463.651215,5.584629,493.677652,253.480698
9,01 01 2018 01:30,439.725708,5.523228,475.706783,258.723785
10,01 01 2018 01:40,498.181702,5.724116,535.841397,251.850998
11,01 01 2018 01:50,526.816223,5.934199,603.014077,265.504700
12,01 01 2018 02:00,710.587280,6.547414,824.662514,274.232910
13,01 01 2018 02:10,655.194275,6.199746,693.472641,266.733185
14,01 01 2018 02:20,754.762512,6.505383,808.098138,266.760406
15,01 01 2018 02:30,790.173279,6.634116,859.459021,270.493195
16,01 01 2018 02:40,742.985291,6.378913,759.434537,266.593292
17,01 01 2018 02:50,748.229614,6.446653,785.281010,265.571808
18,01 01 2018 03:00,736.647827,6.415083,773.172863,261.158691
19,01 01 2018 03:10,787.246216,6.437531,781.771216,257.560211
20,01 01 2018 03:20,722.864075,6.220024,700.764700,255.926498
21,01 01 2018 03:30,935.033386,6.898026,970.736627,250.012894
22,01 01 2018 03:40,1220.609009,7.609711,1315.048928,255.985703
23,01 01 2018 03:50,1053.771973,7.288356,1151.265744,255.444595
24,01 01 2018 04:00,1493.807983,7.943102,1497.583724,256.407410
25,01 01 2018 04:10,1724.488037,8.376162,1752.199662,252.412598
26,01 01 2018 04:20,1636.935059,8.236958,1668.470707,247.979401
27,01 01 2018 04:30,1385.488037,7.879591,1461.815791,238.609604
28,01 01 2018 04:40,1098.932007,7.101376,1062.285034,245.095596
29,01 01 2018 04:50,1021.458008,6.955307,995.995855,245.410202
...,...,...,...,...,...
50500,31 12 2018 19:00,529.938904,5.197528,386.049437,97.632187
50501,31 12 2018 19:10,877.915283,5.782113,553.935635,90.309258
50502,31 12 2018 19:20,711.683228,5.478546,462.849436,87.520317
50503,31 12 2018 19:30,992.034119,6.146048,674.375292,84.240913
50504,31 12 2018 19:40,1574.197998,7.936307,1493.735939,78.987038
50505,31 12 2018 19:50,1706.860962,8.350188,1736.454419,79.042793
50506,31 12 2018 20:00,1731.552979,8.674524,1936.655737,78.169724
50507,31 12 2018 20:10,1592.900024,8.135880,1608.743387,78.773773
50508,31 12 2018 20:20,1403.121948,7.486556,1251.008410,80.061111
50509,31 12 2018 20:30,1433.415039,7.493729,1254.728650,81.279243
50510,31 12 2018 20:40,1550.709961,7.724678,1376.495123,79.519127
50511,31 12 2018 20:50,2062.549072,8.986495,2135.288428,81.056862
50512,31 12 2018 21:00,2309.875000,9.714014,2601.071371,80.272682
50513,31 12 2018 21:10,1901.602051,8.498631,1827.149165,79.394409
50514,31 12 2018 21:20,2240.629883,9.635618,2543.911219,79.356262
50515,31 12 2018 21:30,1814.355957,8.472826,1811.263260,79.699562
50516,31 12 2018 21:40,1992.348999,8.433422,1787.100338,80.132507
50517,31 12 2018 21:50,2554.377930,9.976660,2777.504103,80.081612
50518,31 12 2018 22:00,2681.270020,10.416830,3025.199012,80.452248
50519,31 12 2018 22:10,3019.893066,10.713670,3161.693967,80.960693
50520,31 12 2018 22:20,2771.110107,10.154550,2884.512812,82.335197
50521,31 12 2018 22:30,3333.819092,12.067660,3532.081496,81.985901
50522,31 12 2018 22:40,3455.282959,12.195660,3549.150371,82.210617
50523,31 12 2018 22:50,3429.021973,12.492510,3578.567804,82.111870
50524,31 12 2018 23:00,3514.269043,12.559170,3583.288363,80.495262
50525,31 12 2018 23:10,2963.980957,11.404030,3397.190793,80.502724
50526,31 12 2018 23:20,1684.353027,7.332648,1173.055771,84.062599
50527,31 12 2018 23:30,2201.106934,8.435358,1788.284755,84.742500
50528,31 12 2018 23:40,2515.694092,9.421366,2418.382503,84.297913
50529,31 12 2018 23:50,2820.466064,9.979332,2779.184096,82.274620

In [6]:
dataset.head()

,﻿Date/Time,LV ActivePower (kW),Wind Speed (m/s),Theoretical_Power_Curve (KWh),Wind Direction (°)
0,01 01 2018 00:00,380.047791,5.311336,416.328908,259.994904
1,01 01 2018 00:10,453.769196,5.672167,519.917511,268.641113
2,01 01 2018 00:20,306.376587,5.216037,390.900016,272.564789
3,01 01 2018 00:30,419.645905,5.659674,516.127569,271.258087
4,01 01 2018 00:40,380.650696,5.577941,491.702972,265.674286

In [7]:
dataset.describe()

,LV ActivePower (kW),Wind Speed (m/s),Theoretical_Power_Curve (KWh),Wind Direction (°)
count,50530.000000,50530.000000,50530.000000,50530.000000
mean,1307.684332,7.557952,1492.175463,123.687559
std,1312.459242,4.227166,1368.018238,93.443736
min,-2.471405,0.000000,0.000000,0.000000
25%,50.677890,4.201395,161.328167,49.315437
50%,825.838074,7.104594,1063.776283,73.712978
75%,2482.507568,10.300020,2964.972462,201.696720
max,3618.732910,25.206011,3600.000000,359.997589

In [8]:
dataset.fillna(dataset.mean(),inplace=True)

,﻿Date/Time,LV ActivePower (kW),Wind Speed (m/s),Theoretical_Power_Curve (KWh),Wind Direction (°)
0,01 01 2018 00:00,380.047791,5.311336,416.328908,259.994904
1,01 01 2018 00:10,453.769196,5.672167,519.917511,268.641113
2,01 01 2018 00:20,306.376587,5.216037,390.900016,272.564789
3,01 01 2018 00:30,419.645905,5.659674,516.127569,271.258087
4,01 01 2018 00:40,380.650696,5.577941,491.702972,265.674286
5,01 01 2018 00:50,402.391998,5.604052,499.436385,264.578613
6,01 01 2018 01:00,447.605713,5.793008,557.372363,266.163605
7,01 01 2018 01:10,387.242188,5.306050,414.898179,257.949493
8,01 01 2018 01:20,463.651215,5.584629,493.677652,253.480698
9,01 01 2018 01:30,439.725708,5.523228,475.706783,258.723785
10,01 01 2018 01:40,498.181702,5.724116,535.841397,251.850998
11,01 01 2018 01:50,526.816223,5.934199,603.014077,265.504700
12,01 01 2018 02:00,710.587280,6.547414,824.662514,274.232910
13,01 01 2018 02:10,655.194275,6.199746,693.472641,266.733185
14,01 01 2018 02:20,754.762512,6.505383,808.098138,266.760406
15,01 01 2018 02:30,790.173279,6.634116,859.459021,270.493195
16,01 01 2018 02:40,742.985291,6.378913,759.434537,266.593292
17,01 01 2018 02:50,748.229614,6.446653,785.281010,265.571808
18,01 01 2018 03:00,736.647827,6.415083,773.172863,261.158691
19,01 01 2018 03:10,787.246216,6.437531,781.771216,257.560211
20,01 01 2018 03:20,722.864075,6.220024,700.764700,255.926498
21,01 01 2018 03:30,935.033386,6.898026,970.736627,250.012894
22,01 01 2018 03:40,1220.609009,7.609711,1315.048928,255.985703
23,01 01 2018 03:50,1053.771973,7.288356,1151.265744,255.444595
24,01 01 2018 04:00,1493.807983,7.943102,1497.583724,256.407410
25,01 01 2018 04:10,1724.488037,8.376162,1752.199662,252.412598
26,01 01 2018 04:20,1636.935059,8.236958,1668.470707,247.979401
27,01 01 2018 04:30,1385.488037,7.879591,1461.815791,238.609604
28,01 01 2018 04:40,1098.932007,7.101376,1062.285034,245.095596
29,01 01 2018 04:50,1021.458008,6.955307,995.995855,245.410202
...,...,...,...,...,...
50500,31 12 2018 19:00,529.938904,5.197528,386.049437,97.632187
50501,31 12 2018 19:10,877.915283,5.782113,553.935635,90.309258
50502,31 12 2018 19:20,711.683228,5.478546,462.849436,87.520317
50503,31 12 2018 19:30,992.034119,6.146048,674.375292,84.240913
50504,31 12 2018 19:40,1574.197998,7.936307,1493.735939,78.987038
50505,31 12 2018 19:50,1706.860962,8.350188,1736.454419,79.042793
50506,31 12 2018 20:00,1731.552979,8.674524,1936.655737,78.169724
50507,31 12 2018 20:10,1592.900024,8.135880,1608.743387,78.773773
50508,31 12 2018 20:20,1403.121948,7.486556,1251.008410,80.061111
50509,31 12 2018 20:30,1433.415039,7.493729,1254.728650,81.279243
50510,31 12 2018 20:40,1550.709961,7.724678,1376.495123,79.519127
50511,31 12 2018 20:50,2062.549072,8.986495,2135.288428,81.056862
50512,31 12 2018 21:00,2309.875000,9.714014,2601.071371,80.272682
50513,31 12 2018 21:10,1901.602051,8.498631,1827.149165,79.394409
50514,31 12 2018 21:20,2240.629883,9.635618,2543.911219,79.356262
50515,31 12 2018 21:30,1814.355957,8.472826,1811.263260,79.699562
50516,31 12 2018 21:40,1992.348999,8.433422,1787.100338,80.132507
50517,31 12 2018 21:50,2554.377930,9.976660,2777.504103,80.081612
50518,31 12 2018 22:00,2681.270020,10.416830,3025.199012,80.452248
50519,31 12 2018 22:10,3019.893066,10.713670,3161.693967,80.960693
50520,31 12 2018 22:20,2771.110107,10.154550,2884.512812,82.335197
50521,31 12 2018 22:30,3333.819092,12.067660,3532.081496,81.985901
50522,31 12 2018 22:40,3455.282959,12.195660,3549.150371,82.210617
50523,31 12 2018 22:50,3429.021973,12.492510,3578.567804,82.111870
50524,31 12 2018 23:00,3514.269043,12.559170,3583.288363,80.495262
50525,31 12 2018 23:10,2963.980957,11.404030,3397.190793,80.502724
50526,31 12 2018 23:20,1684.353027,7.332648,1173.055771,84.062599
50527,31 12 2018 23:30,2201.106934,8.435358,1788.284755,84.742500
50528,31 12 2018 23:40,2515.694092,9.421366,2418.382503,84.297913
50529,31 12 2018 23:50,2820.466064,9.979332,2779.184096,82.274620

In [9]:
dataset.isnull().sum()

﻿Date/Time                       0
LV ActivePower (kW)              0
Wind Speed (m/s)                 0
Theoretical_Power_Curve (KWh)    0
Wind Direction (°)               0
dtype: int64

In [10]:
x=dataset.iloc[:,1:3].values

In [11]:
x

array([[  380.04779053,     5.31133604],
       [  453.76919556,     5.67216682],
       [  306.37658691,     5.2160368 ],
       ...,
       [ 2201.10693359,     8.43535805],
       [ 2515.6940918 ,     9.42136574],
       [ 2820.46606445,     9.97933197]])

In [12]:
y=dataset.iloc[:,3].values

In [13]:
y

array([  416.32890782,   519.91751106,   390.90001581, ...,  1788.28475526,
        2418.38250336,  2779.18409628])

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
labelencoder_x=LabelEncoder()

In [16]:
x[:,1]=labelencoder_x.fit_transform(x[:,1])

In [17]:
x

array([[   380.04779053,  16826.        ],
       [   453.76919556,  18338.        ],
       [   306.37658691,  16500.        ],
       ...,
       [  2201.10693359,  31230.        ],
       [  2515.6940918 ,  34908.        ],
       [  2820.46606445,  36796.        ]])

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
#Apply normalization to rescale the features to a standard range of values.
#Normalize the numeric variables from column2 to column 31 in the dataframe
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[ 0.10563314,  0.33448632],
       [ 0.1259914 ,  0.36454358],
       [ 0.08528875,  0.32800573],
       ...,
       [ 0.60852085,  0.62082538],
       [ 0.69539448,  0.69394084],
       [ 0.77955763,  0.73147265]])

In [20]:
#Splitting the dataset into Training set and Test set
from sklearn import cross_validation, neighbors
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

C:\Users\Sai\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [21]:
x_train

array([[  2.42285400e+02,   1.63200000e+04],
       [  7.82544678e+02,   2.10390000e+04],
       [  3.79407898e+02,   1.59840000e+04],
       ...,
       [  4.03746414e+00,   7.80400000e+03],
       [  3.33455688e+02,   1.71710000e+04],
       [  2.17505591e+03,   3.41600000e+04]])

In [22]:
y_train = y_train.astype('int')
y_train

array([ 377,  710,  355, ...,   16,  437, 2276])

In [23]:
x_test

array([[  3597.60400391,  43905.        ],
       [  3601.50195312,  49925.        ],
       [  1198.50695801,  25288.        ],
       ...,
       [  2557.84204102,  38626.        ],
       [  1649.8659668 ,  31208.        ],
       [  2883.1640625 ,  39488.        ]])

In [24]:
y_test

array([ 3582.20464281,  3600.        ,  1072.83105331, ...,  3088.92444299,
        1785.06240833,  3210.15833175])

In [25]:
from sklearn.linear_model import LinearRegression
mlr=LinearRegression()

In [26]:
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [27]:
y_pred=mlr.predict(x_test)

In [28]:
mlr.intercept_

-484.28959692954436

In [29]:
x_train.shape

(40424, 2)

In [30]:
x_test.shape

(10106, 2)

In [31]:
mlr.coef_

array([ 0.40625515,  0.05739114])

In [32]:
pre=mlr.predict([[ 576.65698242,19624]])

In [33]:
pre

array([ 876.22406242])

In [34]:
from sklearn.metrics import r2_score

In [35]:
r2_score(y_test,y_pred)

0.95969595657864804